# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("books.proto", :syntax => :proto3) do
    add_message "books.Book" do
      optional :id, :int32, 1
      optional :title, :string, 2
      optional :description, :string, 3
      repeated :tags, :string, 4
      optional :price, :float, 5
    end
    add_message "books.Books" do
      repeated :books, :message, 1, "books.Book"
    end
    add_message "books.EmptyParams" do
    end
    add_message "books.BookID" do
      optional :id, :int32, 1
    end
    add_message "books.BookNotFound" do
      optional :message, :string, 1
    end
  end
end

module Books
  Book = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("books.Book").msgclass
  Books = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("books.Books").msgclass
  EmptyParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("books.EmptyParams").msgclass
  BookID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("books.BookID").msgclass
  BookNotFound = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("books.BookNotFound").msgclass
end
